# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: DirtyMoliaCI - Dev/1.20.2

on:
  push:
    branches: [ "dev/1.20.2" ]
  pull_request:
    branches: [ "dev/1.20.2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up git
      run: git config --global user.email "noreply@github.com" && git config --global user.name "ci"
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup project
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: applyPatches
    - name: Build project to paperclip jar
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: createReobfPaperclipJar
    - name: Capture build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: build/libs/
    - name: Rename jar file
      run: mv build/libs/Molia-paperclip-1.20.2-R0.1-SNAPSHOT-reobf.jar build/libs/molia-1.20.2-dirty-paperclip.jar
    - name: Release Artifacts
      uses: svenstaro/upload-release-action@v2
      with:
       release_name: "DirtyMolia MC1.20.2 - ${{ github.event.repository.updated_at}}"
       tag: "1.20.1-${{ github.run_id }}"
       repo_token: "${{ secrets.GITHUB_TOKEN }}"
       file: "build/libs/molia-1.20.2-dirty-paperclip.jar"
       file_glob: true
       prerelease: false    
